//! Render the typed ecosystem manifest as queryable artifacts.
//!
//! The manifest at `pleme-io/nix/lib/ecosystem.nix` is the typed
//! source of truth for the fleet's apps × classes × profiles. This
//! module extracts that knowledge into renderable forms:
//!
//!   - Markdown table (for embedding in CLAUDE.md / docs)
//!   - JSON (for tooling)
//!   - DOT graph (for visualization)
//!
//! Per the Compounding Directive: derived knowledge is generated
//! mechanically, never hand-written. When the manifest changes, every
//! render output regenerates. No drift possible.

use crate::check::ManifestSnapshot;
use anyhow::{anyhow, Result};
use std::collections::BTreeMap;
use std::path::Path;

/// Load the manifest snapshot via `nix eval --json`. Identical
/// invocation to ManifestMembershipChecker but shared here for render
/// commands that don't go through the audit path.
pub fn load_manifest(manifest_path: &Path) -> Result<ManifestSnapshot> {
    let workspace_root = manifest_path
        .parent()
        .and_then(|p| p.parent())
        .and_then(|p| p.parent())
        .ok_or_else(|| anyhow!("manifest path has no workspace ancestor"))?;
    let expr = format!(
        r#"
          let
            lib = (import <nixpkgs> {{}}).lib;
            eco = import {} {{ inputs = {{}}; lib = lib; }};
          in {{
            resolved = lib.mapAttrs (_: app: {{
              class = app.class or null;
              namespace = app.namespace or "programs";
              optionName = app.optionName or "";
              platforms = app.platforms or [];
            }}) eco.resolved;
            classes = lib.mapAttrs (_: cls: {{
              profiles = cls.profiles or [];
              auditOnly = cls.auditOnly or false;
            }}) eco.classes;
          }}
        "#,
        manifest_path.display(),
    );
    let output = std::process::Command::new("nix")
        .args(&["eval", "--impure", "--json", "--expr", &expr])
        .current_dir(workspace_root)
        .output()?;
    if !output.status.success() {
        return Err(anyhow!(
            "nix eval failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let stdout = String::from_utf8(output.stdout)?;
    Ok(serde_json::from_str(&stdout)?)
}

/// Render the manifest as a Markdown table.
///
/// Format:
///   | App | Class | Namespace | Profiles | Audit-only |
pub fn render_markdown_table(manifest: &ManifestSnapshot) -> String {
    let mut out = String::new();
    out.push_str("# pleme-io fleet — typed app manifest\n\n");
    out.push_str(
        "*Generated by `cse-lint render fleet-table`. Do not hand-edit; \
         changes go to `pleme-io/nix/lib/ecosystem.nix`.*\n\n",
    );

    // Group apps by class for readable organization.
    let mut by_class: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for (app_name, app) in &manifest.resolved {
        let class = app.class.clone().unwrap_or_else(|| "<unclassed>".into());
        by_class.entry(class).or_default().push(app_name.as_str());
    }
    // Sort apps within each class
    for apps in by_class.values_mut() {
        apps.sort();
    }

    out.push_str("| Class | App | Namespace | Profiles | Audit-only |\n");
    out.push_str("|-------|-----|-----------|----------|------------|\n");
    for (class_name, apps) in &by_class {
        let class = manifest.classes.get(class_name);
        let profiles = class
            .map(|c| c.profiles.join(", "))
            .unwrap_or_else(|| "—".into());
        let audit = class
            .map(|c| if c.audit_only { "✓" } else { "" })
            .unwrap_or("");
        for app_name in apps {
            let app = manifest.resolved.get(*app_name);
            let ns = app
                .and_then(|a| a.namespace.as_deref())
                .unwrap_or("programs");
            let opt = app
                .and_then(|a| a.option_name.as_deref())
                .unwrap_or(app_name);
            out.push_str(&format!(
                "| `{}` | `{}` | `{}.{}` | {} | {} |\n",
                class_name, app_name, ns, opt, profiles, audit,
            ));
        }
    }

    out.push_str("\n## Class definitions\n\n");
    out.push_str("| Class | Profiles | Audit-only |\n");
    out.push_str("|-------|----------|------------|\n");
    for (cls_name, cls) in &manifest.classes {
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            cls_name,
            if cls.profiles.is_empty() {
                "—".into()
            } else {
                cls.profiles.join(", ")
            },
            if cls.audit_only { "✓" } else { "" },
        ));
    }

    out
}

/// Render the manifest as JSON (pretty-printed for human review;
/// downstream tooling can pipe through `jq`).
pub fn render_json(manifest: &ManifestSnapshot) -> Result<String> {
    Ok(serde_json::to_string_pretty(manifest)?)
}

/// Render the manifest as a Graphviz DOT graph: classes as boxes,
/// profiles as ovals, edges from class → profile.
pub fn render_dot(manifest: &ManifestSnapshot) -> String {
    let mut out = String::new();
    out.push_str("digraph pleme_io_ecosystem {\n");
    out.push_str("  rankdir=LR;\n");
    out.push_str("  node [shape=box, fontname=\"monospace\"];\n");

    // Classes as boxes with their apps listed
    let mut by_class: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for (app_name, app) in &manifest.resolved {
        let class = app.class.clone().unwrap_or_else(|| "<unclassed>".into());
        by_class.entry(class).or_default().push(app_name.as_str());
    }

    for (cls_name, apps) in &by_class {
        let class_meta = manifest.classes.get(cls_name);
        let audit = class_meta.map(|c| c.audit_only).unwrap_or(false);
        let style = if audit {
            "style=dashed,color=gray"
        } else {
            "style=filled,fillcolor=lightblue"
        };
        let label = format!(
            "{}\\n────\\n{}",
            cls_name,
            apps.iter().take(8).copied().collect::<Vec<_>>().join("\\n")
        );
        out.push_str(&format!("  \"class_{}\" [{}, label=\"{}\"];\n", cls_name, style, label));
    }

    // Profiles as ovals
    let mut profiles: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for cls in manifest.classes.values() {
        for p in &cls.profiles {
            profiles.insert(p.clone());
        }
    }
    out.push_str("  subgraph cluster_profiles {\n    label=\"profiles\";\n");
    for p in &profiles {
        out.push_str(&format!(
            "    \"profile_{}\" [shape=oval, style=filled, fillcolor=lightyellow, label=\"{}\"];\n",
            p, p
        ));
    }
    out.push_str("  }\n");

    // Edges: class → profile
    for (cls_name, cls) in &manifest.classes {
        for p in &cls.profiles {
            out.push_str(&format!(
                "  \"class_{}\" -> \"profile_{}\";\n",
                cls_name, p
            ));
        }
    }
    out.push_str("}\n");
    out
}
